### ISSUE TITLE
unable to select channel in mda widget if is widget loaded before cfg

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/pymmcore-widgets#125]
not sure if this is widgets or napari-micromanager, but i suspect widgets:

if I open the mda widget before loading a system config, I seem to be never able to add a channel later, even after loading a config:

https://user-images.githubusercontent.com/1609449/220792317-39c0a121-00ec-448a-a6d9-57c770e3ebec.mov

if I do it in the reverse order, it's fine:

https://user-images.githubusercontent.com/1609449/220792345-97662413-3d7f-4bff-a0f4-73f06b3dbb47.mov

**Comment by fdrgsp** [comment]
yes, this should be solved with #113  I think.

**Comment by tlambert03** [comment]
yep! thanks
