### ISSUE TITLE
transfer to pymmcore-plus repo

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/pymmcore-widgets#13]
I've created a new organization https://github.com/pymmcore-plus so we can keep all of these associated projects together.

I'm moving useq-schema, pymmcore-plus, and napari-micromanager out of my personal repo into that org, and we should do it with this one too.

you can do it in settings -> transfer repo

**Comment by fdrgsp** [comment]
@tlambert03 moved.
