### ISSUE TITLE
reminder: review shutter_widget.py and set_pixel_size_widget.py

### ISSUE THREAD

**Issue by fdrgsp** [pymmcore-plus/pymmcore-widgets#15]
Review [shutter_widget.py](https://github.com/pymmcore-plus/pymmcore-widgets/blob/main/src/pymmcore_widgets/shutter_widget.py) and [set_pixel_size_widget.py](https://github.com/pymmcore-plus/pymmcore-widgets/blob/main/src/pymmcore_widgets/set_pixel_size_widget.py).

Old PR form `napari-micromanager`:
- https://github.com/pymmcore-plus/napari-micromanager/pull/161
- https://github.com/pymmcore-plus/napari-micromanager/pull/141

**Comment by tlambert03** [comment]
closing this, since these can now be added as new PRs
