### ISSUE TITLE
Pass step size to a StageWidget?

### ISSUE THREAD

**Issue by dpshepherd** [pymmcore-plus/pymmcore-widgets#240]
When creating a new StageWidget for a custom GUI, is there a way to pass in a step size to override the default? We have a piezo stage that I would like to set the default to something smaller than 10 (0.1 specifically). I looked at the docs and the function docstring, but didn't see anything immediately.

Or maybe the preferred way to do this to create the Widget then set the step size? If so, can you point me in the right direction to do this when using just a StageWidget?

Thanks!

**Comment by tlambert03** [comment]
looks like that hasn't been publicly exposed, but absolutely should.  I'll add it now

**Comment by tlambert03** [comment]
v0.5.6 contains the fix and is building and deploying to PyPI currently.  should be up in ~15 mins or so.  cheers!

**Comment by dpshepherd** [comment]
Wow, instant. Shouldn't you both be out getting some candy? 🤣

Thank you!!
