### ISSUE TITLE
Allow Config Groups to be Renamed

### ISSUE THREAD

**Issue by gselzer** [pymmcore-plus/pymmcore-widgets#324]
* pymmcore-widgets version: 0.7.2
* Python version: 3.12.4
* Operating System: Windows 11

### Description

Is there a reason why we cannot rename config groups by clicking the `Edit` button with a group selected?

### What I Did

With the demo config active, I clicked the `Camera` group, and then clicked the `Edit` button. There's a `QLineEdit` for the group name, but it cannot be edited.

![image](https://github.com/user-attachments/assets/8909f5d2-3bfa-414f-a201-57eafc3d1114)

**Comment by fdrgsp** [comment]
Thanks @gselzer! This is actually a bug. I just fixed it [here](https://github.com/fdrgsp/pymmcore-widgets/tree/fix-edit-group) so if you want to try it out you can pip install this branch: 
```
pip install git+https://github.com/fdrgsp/pymmcore-widgets@fix-edit-group
```

**Comment by tlambert03** [comment]
@fdrgsp, if you have a proposed fix, it's best to open a PR, and then people can very easily `gh co #NUMBER`

**Comment by fdrgsp** [comment]
👍🏻 here's the PR #328
