### ISSUE TITLE
Stage Control - consider absolute position field

### ISSUE THREAD

**Issue by gselzer** [pymmcore-plus/pymmcore-widgets#332]
* pymmcore-widgets version: 0.7.2
* Python version: 3.12.4
* Operating System: Windows 11

### Description

A colleague noted that sometimes he knows exactly where he wants a stage to be positioned, and suggested it would be nice to enter the absolute stage position somewhere on the widget. One option could be to replace the circled `QLabel` with a couple of `QDoubleSpinBox`es?

![image](https://github.com/user-attachments/assets/46b0f324-32d0-40c3-ad7a-eda14394b86f)

**Comment by tlambert03** [comment]
i'm working on the stage widget at the moment. can add that while working on #331
