### ISSUE TITLE
Saving MDASequence as YAML crashes if PyYAML not installed

### ISSUE THREAD

**Issue by gselzer** [pymmcore-plus/pymmcore-widgets#333]
* pymmcore-widgets version: 0.7.2
* Python version: 3.12.4
* Operating System: Windows 11

### Description

By default, PyYAML is not installed (it's an [extension of `useq-schema`](https://github.com/pymmcore-plus/useq-schema/blob/3eea067cfbc922bcd602c18d164c4be446f0d062/pyproject.toml#L40)). If you try to [save a MDASequence](https://github.com/pymmcore-plus/pymmcore-widgets/blob/5957860901237424a297096b4817e80f30927605/src/pymmcore_widgets/useq_widgets/_mda_sequence.py#L451) as YAML, it'll crash. 

Ideally, we'd either always depend upon PyYAML or we'd disallow saving as YAML if it is not installed.

**Comment by tlambert03** [comment]
yeah, at the very least, that line should be in a try catch.

also: a general comment about "crashing" in Qt.  The general assumption is that these widgets will be used in a broader app, and in python, it's best practice to override `sys.excepthook` when you're creating an application with Qt (unless you specifically *want* an unraised exception to crash out to the console).  You can see a similar PR I made to @fdrgsp 's repo here: https://github.com/fdrgsp/micromanager-gui/pull/16 and I suggest you add similar logic to your [launch command](https://github.com/gselzer/pymmcore-plus-sandbox/blob/7fae9eab2b6063a879a14a29a915ae8a2361ed68/src/pymmcore_plus_sandbox/__init__.py#L438)
