### ISSUE TITLE
MDA Save button is ambiguous

### ISSUE THREAD

**Issue by gselzer** [pymmcore-plus/pymmcore-widgets#335]
* pymmcore-widgets version: 0.7.2
* Python version: 3.12.4
* Operating System: Windows 11

### Description

A colleague noted that the `Save` button on the `MDAWidget` is not particularly clear - he didn't know if "Save" pertained to the MDA parameters or to the acquired images. Could we think of some addition (either changing the button text or adding a label) that could make it clearer that the parameters can be saved/loaded?

**Comment by tlambert03** [comment]
Sure, "Save Settings?"  "Save MDA?"  "Save parameters?"

**Comment by gselzer** [comment]
Hmm - I think either of "Save Settings", `Save Param(eter)s" would be great!

**Comment by tlambert03** [comment]
care to join us as a contributor? :)

**Comment by gselzer** [comment]
> care to join us as a contributor? :) 

Absolutely, once I finish converting this long list of action items (which includes this point) into issues I'd love to contribute!

**Comment by tlambert03** [comment]
ok 😄 ... can I leave this particular issue for you then?
