### ISSUE TITLE
MDAWidget TimePlanWidget IntColumn Maximum 10,000 loops

### ISSUE THREAD

**Issue by Gronemeyer** [pymmcore-plus/pymmcore-widgets#393]
### Description

Using the MDAWidget and auto setting an MDA sequence object. Acquisitions requiring more than 10,000 frames cannot be launched from the MDAWidget

### What I Did
I changed the maximum value for the `IntColumn` dataclass used by the useq_widgets `TimePlanWidget` in the MDAWidget

```python
# useq_widgets > _column_info.py > line 279

@dataclass(frozen=True)
class IntColumn(_RangeColumn):
    data_type: WdgGetSet = TableIntWidget
    minimum: int = 0
    maximum: int = 50_000 #was 10_000
```
This works, but I am not familiar with handling frozen dataclasses in python modules--so I imagine this is a hack solution and I do not know what unintended consequences might occur (non as of yet)

**Comment by tlambert03** [comment]
Not a hack solution at all, and 10_000 was clearly just a random magic number.  Would you be able/willing to open a PR to bump it to 99_999?
