### ISSUE TITLE
task: get this on conda-forge

### ISSUE THREAD

**Issue by tlambert03** [pymmcore-plus/pymmcore-widgets#91]
@fdrgsp ... this would be a good thing for you to learn to do :)

**Comment by ianhi** [comment]
Indeed a good skill to know! Also good to know that https://github.com/conda-incubator/grayskull#usage should make this very easy.

**Comment by tlambert03** [comment]
this got done for us by @goanpeca. 👍🙏

https://github.com/conda-forge/staged-recipes/pull/23468
